# Energy deposit of 1 MeV electrons
# in 530 um silicon sensor.
# M.J.Berger et al. NIM 69 (1969) page 181.
# Based on ther GEANT4 Em5 example.
#     		    
/control/verbose 2
/run/verbose 2
/run/initialize
#
/setup/sensor/material G4_Si      
/setup/sensor/thickness 530 um
/setup/sensor/xy 1 cm
/setup/sourceshield/enable 0
/setup/shield/enable 0
/setup/collimator/enable 0
#
/gps/particle e- 
/gps/energy 1 MeV
/gps/direction 0 0 1
/gps/position 0 0 -1 mm
#
# definition of histograms (id, n_bins, min, max, unit)
/analysis/h1/set 0 500 0 20 MeV		#Primary Energy Distribution
/analysis/h1/set 1 500 -10 10 mm	#Primary x Distribution
/analysis/h1/set 2 500 -10 10 mm	#Primary y Distribution
/analysis/h1/set 3 200 0 3 MeV		#Secondary electrons energy distribution (e.g. ion decay)
/analysis/h1/set 4 200 0 200 keV	#Secondary photons energy distribution
/analysis/h1/set 5 100 0 5 GeV		#Shield particle energy distribution (before)
/analysis/h1/set 6 100 0 5 GeV		#Shield particle energy distribution (after)
/analysis/h1/set 7 100 0 200 keV	#Sensor energy deposit
/analysis/h1/set 8 120 0 500 um		#Sensor track length
/analysis/h1/set 9 120 0 30 deg		#Sensor track In angle
/analysis/h1/set 10 120 0 30 deg	#Sensor track Out angle
/analysis/h1/set 11 100 0 200 keV	#Sensor energy deposit (triggered)
/analysis/h1/set 12 100 0 1 keV/um	#Sensor dE/dx
/analysis/setFileName unit_test_2.root 
#
/run/printProgress 100000
# 
/run/beamOn 1000000
